data:
  name: aishell2
  vocab: egs/aishell2/data/vocab
  batch_size: 32
  dataset_type: audio # audio or text
  text: text.split
  train: egs/aishell2/data/train
  test: egs/aishell2/data/test_mic
  dev: egs/aishell2/data/dev
  short_first: False
  num_mel_bins: 40
  apply_cmvn: False
  normalization: True
  spec_augment: True
  from_kaldi: False
  num_works: 4
model:
  # network architecture
  type: transformer
  d_model: 320
  normalize_before: False
  concat_after: False
  # dropout
  pos_dropout_rate: 0.0
  ffn_dropout_rate: 0.0
  slf_attn_dropout_rate: 0.0
  src_attn_dropout_rate: 0.0
  residual_dropout_rate: 0.1
  # encoder related
  feat_dim: 40
  num_enc_blocks: 12
  enc_ffn_units: 1280
  enc_input_layer: conv2d
  # decoder related
  vocab_size: 5246
  num_dec_blocks: 6
  dec_ffn_units: 1280
  # attention related
  n_heads: 4
  # label smoothing
  smoothing: 0.1
  activation: glu
  share_embedding: True
train:
  scheduler: stepwise
  optimizer: adam
  warmup_steps: 25000
  finetuning: True
  shuffle: True
  lr: 1.0
  clip_grad: 5
  epochs: 25
  accum_steps: 2
  grad_noise: False
  load_model: False
  save_name: transformer
